//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.21 at 12:45:33 PM CET 
//


package osmgpxtool.gpxfilter.gpx.schema;

import javax.xml.bind.annotation.XmlRegistry;

import osmgpxtool.gpxfilter.gpx.schema.Gpx.Rte;
import osmgpxtool.gpxfilter.gpx.schema.Gpx.Trk;
import osmgpxtool.gpxfilter.gpx.schema.Gpx.Wpt;
import osmgpxtool.gpxfilter.gpx.schema.Gpx.Rte.Rtept;
import osmgpxtool.gpxfilter.gpx.schema.Gpx.Trk.Trkseg;
import osmgpxtool.gpxfilter.gpx.schema.Gpx.Trk.Trkseg.Trkpt;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gpx_filter.gpx.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gpx_filter.gpx.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Trkpt }
     * 
     */
    public Trkpt createGpxTrkTrksegTrkpt() {
        return new Trkpt();
    }

    /**
     * Create an instance of {@link Trk }
     * 
     */
    public Trk createGpxTrk() {
        return new Trk();
    }

    /**
     * Create an instance of {@link Rte }
     * 
     */
    public Rte createGpxRte() {
        return new Rte();
    }

    /**
     * Create an instance of {@link Trkseg }
     * 
     */
    public Trkseg createGpxTrkTrkseg() {
        return new Trkseg();
    }

    /**
     * Create an instance of {@link Rtept }
     * 
     */
    public Rtept createGpxRteRtept() {
        return new Rtept();
    }

    /**
     * Create an instance of {@link Gpx }
     * 
     */
    public Gpx createGpx() {
        return new Gpx();
    }

    /**
     * Create an instance of {@link Wpt }
     * 
     */
    public Wpt createGpxWpt() {
        return new Wpt();
    }

    /**
     * Create an instance of {@link BoundsType }
     * 
     */
    public BoundsType createBoundsType() {
        return new BoundsType();
    }

}
