//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.22 at 04:45:32 PM CET 
//


package gpx_filter.metadata.schema;

import javax.xml.bind.annotation.XmlRegistry;
import gpx_filter.metadata.schema.GpxFiles.GpxFile;
import gpx_filter.metadata.schema.GpxFiles.GpxFile.Tags;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gpx_filter.metadata.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gpx_filter.metadata.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GpxFile }
     * 
     */
    public GpxFile createGpxFilesGpxFile() {
        return new GpxFile();
    }

    /**
     * Create an instance of {@link GpxFiles }
     * 
     */
    public GpxFiles createGpxFiles() {
        return new GpxFiles();
    }

    /**
     * Create an instance of {@link Tags }
     * 
     */
    public Tags createGpxFilesGpxFileTags() {
        return new Tags();
    }

}
